amazon:
  aws:
    accesskey: [AWS_ACCESS_KEY]
    secretkey: [AWS_SECRET_KEY]
management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:7500/user